openapi: "3.0.3"
info:
  version: 0.0.1
  title: REST API
servers:
  - url: http://localhost:9000
tags:
  - name: user
  - name: version
paths:
  /:
    get:
      summary: "バージョン確認"
      operationId: getVersion
      tags:
        - version
      responses:
        "200":
          description: OK
  /register:
    post:
      summary: "新規ユーザー登録"
      operationId: registerUser
      tags:
        - user
      responses:
        "201":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: sample@test.com
                password:
                  type: string
                  format: password
                  example: Hoge1357
              required:
                - email
                - password
  /user/{firebase_uid}:
    delete:
      summary: "ユーザーの削除"
      operationId: deleteUser
      tags:
        - user
      parameters:
        - name: firebase_uid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: user {firebase_uid} deleted
